CREATE TABLE load_test (
  id INT AUTO_INCREMENT PRIMARY KEY,
  i VARCHAR(32),
  data VARCHAR(128)
) ENGINE=MEMORY;

CREATE TABLE load_test_where (
  id INT AUTO_INCREMENT PRIMARY KEY,
  i VARCHAR(32),
  data VARCHAR(128),
  INDEX idx_i (i)
) ENGINE=MEMORY;
